### ISSUE TITLE
Dependencies in CMakeLists.txt and package.xml

### ISSUE THREAD

**Issue by cdondrup** [strands-project/data_compression#8]
@nilsbore After I commented on the commit with the include directory I noticed that you specify your dependencies in a quite unusual way. You might want to think of using find_package for opencv and cv_bridge: e.g. `find_package(OpenCV REQUIRED)` `find_package(catkin REQUIRED cv_bridge)`. And also define it as a build and run time dependecy in the package.xml instead of using absolute paths for linking and includes.

**Comment by nilsbore** [comment]
@cdondrup I did this because those specific nodes have no other dependencies on ros and since ros/groovy should be installed in the same place on all machines. The reasoning is that someone may want to run it without ros, just using opencv. But I recognize that this might fail in instances where users have specified other install paths of ros. The most reasonable thing would probably be to comment these lines and use the catkin depencies instead.

**Comment by cdondrup** [comment]
That's right. In my opinion it should be as generally applicable as possible. Also as long as it is in the strands repository I imagine that everyone will use it with ros.

**Comment by nilsbore** [comment]
The above pull request solves this issue, closing.
